# Generated by Django 3.2.3 on 2021-05-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210526_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_of_day',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='number_of_trip',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
