# Generated by Django 3.2.3 on 2021-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210528_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='transports',
            field=models.ManyToManyField(blank=True, to='api.transport'),
        ),
    ]
