# Generated by Django 3.2.3 on 2021-05-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tarif_transports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='transports',
            field=models.ManyToManyField(to='api.transport'),
        ),
    ]
